@ECHO OFF

SET SCRIPT_FOLDER=%~dp0
SET SCRIPT_FOLDER=%SCRIPT_FOLDER:~,-1%
CD /D %SCRIPT_FOLDER%

SET WINSDK_10_BIN_X64=
SET WINSDK_10_BIN_ROOT=%ProgramFiles(x86)%\Windows Kits\10\bin
FOR /F "tokens=1*" %%A IN ('dir /b /O:-N "%WINSDK_10_BIN_ROOT%\10.*"') DO (
	IF EXIST "%WINSDK_10_BIN_ROOT%\%%A\x64\tracelog.exe" (
		SET "WINSDK_10_BIN_X64=%WINSDK_10_BIN_ROOT%\%%A\x64"
		GOTO FOUND_WINSDK_10_BIN_X64
	)
)

ECHO Failed to find WinSDK tracelog.exe under "%WINSDK_10_BIN_ROOT%"
SET ERRORLEVEL=1
GOTO :EOF

:FOUND_WINSDK_10_BIN_X64
SET TRACELOG_EXE=%WINSDK_10_BIN_X64%\tracelog.exe
SET TRACEFMT_EXE=%WINSDK_10_BIN_X64%\tracefmt.exe
SET ERRORLEVEL=0
