
name: p4vfs-build

inputs:
  workspace:
    required: True
  configuration:
    required: False
    default: Release
  solution:
    required: False
    default: source/P4VFS.sln

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

permissions:
  contents: read
  
runs:
  using: "composite"
  steps:
  - name: Set image info in env
    shell: pwsh
    run: |
      Write-Output "ImageOS=$env:ImageOS" >> $env:GITHUB_ENV
      Write-Output "ImageVersion=$env:ImageVersion" >> $env:GITHUB_ENV

  - name: Setup MSBuild
    uses: microsoft/setup-msbuild@v2
    with:
      msbuild-architecture: x64

  - name: Cache OpenSSL ${{env.ImageOS}} ${{env.ImageVersion}}
    uses: actions/cache@v4.0.2
    with:
      path: |
        external/OpenSSL
        !external/OpenSSL/OpenSSL.Module.cs
      key: build-openssl-${{env.ImageOS}}-${{env.ImageVersion}}-${{ hashFiles('external/OpenSSL/OpenSSL.Module.cs') }}

  - name: Build ${{matrix.configuration}}
    shell: pwsh
    working-directory: ${{inputs.workspace}}
    run: msbuild.exe -clp:Summary -nologo -nodeReuse:false -verbosity:m -restore -maxcpucount "-p:Configuration=${{inputs.configuration}}" -p:Platform=x64 ${{inputs.solution}}
